import { escapeHtml as e, type Action, type Resource } from '../core.js';
import { conversationPanel, page, renderAction, renderMarkdown, renderPlan } from '../render.js';
import type { Visitor, Workspace } from '../store.js';
import { localDate, vaultResolver } from './resources.js';
import type { VaultRuntime } from './runtime.js';

export function todayCanvas(workspace: Workspace, visitor: Visitor, runtime: VaultRuntime): string {
  const resolve = vaultResolver(runtime);
  const day = localDate();
  const root = resolve('/vault');
  const diagnosticNotice = Number(root.facts.Errors) > 0 ? `<aside class="notice review-notice" role="status"><strong>${e(root.facts.Errors)} vault validation error(s).</strong> Invalid records are not shown or actionable. Fix the affected files and reload; an empty collection may not mean there is no work.<details><summary>Validation details</summary><pre>${e(root.facts.Diagnostics ?? '')}</pre></details></aside>` : '';
  const link = (href: string) => `${href}${href.includes('?') ? '&' : '?'}workspace=${encodeURIComponent(workspace.id)}`;
  const navigation = `<nav class="scope-nav" aria-label="Vault"><a href="/today" aria-current="page">Today</a>${[['/vault/tasks', 'Tasks'], ['/vault/calendar', 'Calendar'], ['/vault/journal', 'Journal'], ['/vault/para', 'PARA'], ['/vault', 'All resources']].map(([href, title]) => `<a href="${e(link(href!))}">${e(title)}</a>`).join('')}<a href="/vault/apps">App review</a></nav>`;
  const heading = `<div class="workspace-heading today-heading"><div><p class="eyebrow">YOUR DAY / LOCAL MARKDOWN</p><h1>${e(workspace.plan.title)}</h1><p class="lead">${e(new Date(`${day}T12:00:00`).toLocaleDateString(undefined, { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' }))}</p></div><span class="engine-badge">APPROVED FILES · LIVE RESOURCES</span></div>${navigation}${diagnosticNotice}`;
  const defaults = ['/vault/today', '/vault/tasks', '/vault/journal', '/vault/para'];
  const defaultPlan = workspace.plan.layout === 'stack' && workspace.plan.blocks.length === defaults.length && workspace.plan.blocks.every((block, index) => block.resource === defaults[index] && block.view === 'list');
  const undo = workspace.previousPlan ? `<form class="undo-layout" method="post" action="/workspaces/${e(workspace.id)}/undo"><input type="hidden" name="csrf" value="${e(visitor.csrf)}"><input type="hidden" name="revision" value="${workspace.revision}"><button>Undo last layout change</button><span class="fine">Saved records remain unchanged.</span></form>` : '';
  if (!defaultPlan) return `<div id="canvas" tabindex="-1" data-revision="${workspace.revision}" data-focus="">${heading}<p class="composition-note">${e(workspace.note)}</p>${renderPlan(workspace.plan, resolve, visitor, workspace.id)}${undo}</div>`;

  const tasks = resolve('/vault/tasks'), schedule = resolve('/vault/today'), journals = resolve('/vault/journal'), para = resolve('/vault/para');
  const upcoming = resolve('/vault/calendar');
  const journal = journals.items?.find(item => item.facts.date === day);
  const journalTypeLink = journals.links.find(item => item.rel === 'create');
  const journalType = !journal && journalTypeLink ? resolve(journalTypeLink.href) : undefined;
  const journalAction = journal?.actions.find(action => action.fields.some(field => field.name === 'body'));
  const canWriteJournal = Boolean(journalAction || journalType?.actions.length);
  const selected = (record: Resource) => `<label class="pick"><input type="checkbox" name="selected" form="chat-send" value="${e(record.href)}" aria-label="Select ${e(record.title)}"><span class="sr-only">Select ${e(record.title)}</span></label>`;
  const taskCards = (tasks.items ?? []).map((task, index) => {
    const dateAction = task.actions.find(action => action.fields.some(field => field.valueType === 'date'));
    const dateField = dateAction?.fields.find(field => field.name === 'due') ?? dateAction?.fields.find(field => field.valueType === 'date');
    const dateForm = dateAction && dateField ? renderAction(task, { ...dateAction, title: 'Save date', fields: [dateField] }, visitor, `task-date-${index}`, workspace.id) : '';
    const fixedActions = task.actions.filter(action => action.fields.length === 0);
    const wikiTarget = task.facts.Path?.replace(/\.md$/i, '');
    return `<li class="task-card">${selected(task)}<div class="task-card-heading"><a href="${e(link(task.href))}">${e(task.title)}</a><span class="tag">${e(task.facts.status ?? task.facts.Type)}</span></div><p class="fine">${task.facts.due ? `Due ${e(task.facts.due)}${task.facts.due < day ? ' · overdue' : ''}` : 'No deadline'}${task.facts.scheduled ? ' · scheduled work session' : ''}</p><div class="task-card-actions">${fixedActions.map((action, actionIndex) => renderAction(task, action, visitor, `task-${index}-${actionIndex}`, workspace.id)).join('')}${canWriteJournal && wikiTarget ? `<button type="button" class="journal-insert" data-journal-link="${e(`[[${wikiTarget}]]`)}">Link in journal</button>` : ''}</div>${dateForm ? `<details class="schedule-task"><summary>Set a date</summary>${dateForm}<a class="fine" href="${e(link(task.href))}">Edit Markdown or scheduled time range →</a></details>` : ''}</li>`;
  }).join('');
  const createTask = tasks.links.find(item => item.rel === 'create');
  const taskType = createTask ? resolve(createTask.href) : undefined;
  const taskCreateForm = taskType?.actions[0] ? `<details class="quick-create"><summary>New task +</summary>${renderAction(taskType, taskType.actions[0], visitor, 'today-create-task', workspace.id)}</details>` : '';
  const scheduleItems = (schedule.items ?? []).filter(item => !item.facts.Type?.startsWith('journal.'));
  const scheduleRows = (items: Resource[]) => items.map(item => `<li>${selected(item)}<span class="schedule-time">${e(item.facts.Time ?? item.facts['Calendar date'] ?? 'All day')}</span><div><a href="${e(link(item.href))}">${e(item.title)}</a><span class="fine">${e(item.facts.Type)} · ${e(item.facts['Calendar field'] ?? '')}</span></div></li>`).join('');
  const nextItems = (upcoming.items ?? []).filter(item => item.facts['Calendar date']! > day && !item.facts.Type?.startsWith('journal.')).slice(0, 6);
  let journalContent: string;
  if (journal && journalAction) {
    const bodyAction: Action = { ...journalAction, title: 'Save journal', fields: journalAction.fields.filter(field => field.name === 'body') };
    journalContent = `<p class="fine"><a href="${e(link(journal.href))}">${e(journal.facts.Path)}</a> · existing entry for ${day}</p>${renderAction(journal, bodyAction, visitor, 'today-journal', workspace.id)}<details class="journal-preview"><summary>Saved Markdown preview</summary><div class="markdown-body">${renderMarkdown(journal.body ?? '', journal, workspace.id)}</div></details>`;
  } else if (journal) journalContent = `<p class="fine">This entry is read only with the current permissions.</p><div class="markdown-body">${renderMarkdown(journal.body ?? '', journal, workspace.id)}</div><a href="${e(link(journal.href))}">Open journal entry →</a>`;
  else if (journalType?.actions[0]) {
    const create: Action = { ...journalType.actions[0], title: 'Create today’s journal', fields: journalType.actions[0].fields.map(field => ({ ...field, value: field.name === 'date' ? day : field.name === 'title' ? day : field.value })) };
    journalContent = `<p class="fine">No entry exists for ${day}. Write freely and explicitly create it below. Opening Today never creates a file.</p>${renderAction(journalType, create, visitor, 'today-journal', workspace.id)}`;
  } else journalContent = '<p class="fine">No readable entry for today. Approve the journal’s read/create permissions to use your daily Markdown journal.</p><a href="/vault/apps">Review journal permissions →</a>';
  const groups = ['Projects', 'Areas', 'Resources', 'Archives'].map(folder => {
    const items = (para.items ?? []).filter(item => item.facts.Path?.startsWith(`${folder}/`));
    return `<section class="para-group"><h3>${folder}</h3>${items.length ? `<ul>${items.slice(0, 8).map(item => `<li><a href="${e(link(item.href))}">${e(item.title)}</a></li>`).join('')}</ul>` : '<p class="fine">No approved readable notes.</p>'}</section>`;
  }).join('');
  const approvals = runtime.reviews();
  const pendingCount = approvals.filter(app => app.status !== 'active').length;
  const reviewNotice = pendingCount ? `<p class="notice review-notice">${pendingCount} app definition${pendingCount === 1 ? '' : 's'} need review. No permissions are granted automatically. <a href="/vault/apps">Review exact sources and permissions →</a></p>` : '';
  return `<div id="canvas" tabindex="-1" data-revision="${workspace.revision}" data-focus="">${heading}${reviewNotice}${!root.links.some(link => link.rel === 'type') ? '<p class="empty">Your vault is not active yet. Start with <a href="/vault/apps">App review</a>; only the permissions you explicitly select will be enabled.</p>' : ''}<div class="today-grid"><section class="panel today-schedule"><div class="section-heading"><div><p class="eyebrow">ON THE CALENDAR</p><h2>Today’s schedule</h2></div><a href="${e(link('/vault/calendar'))}">Calendar →</a></div>${scheduleItems.length ? `<ul class="day-schedule">${scheduleRows(scheduleItems)}</ul>` : '<p class="fine">No approved events or scheduled tasks for today.</p>'}<nav class="day-navigation" aria-label="Calendar days"><a href="${e(link(`/vault/calendar?date=${localDate(-1)}`))}">← Yesterday</a><a href="${e(link(`/vault/calendar?date=${localDate(1)}`))}">Tomorrow →</a></nav>${nextItems.length ? `<details class="upcoming" open><summary>Coming up</summary><ul class="day-schedule">${scheduleRows(nextItems)}</ul></details>` : ''}</section><section class="panel today-tasks"><div class="section-heading"><div><p class="eyebrow">MOVE WORK FORWARD</p><h2>Unfinished tasks <span class="tag">${tasks.items?.length ?? 0}</span></h2></div><a href="${e(link('/vault/tasks'))}">All tasks →</a></div>${taskCreateForm}<ul class="today-task-list">${taskCards || '<li class="fine empty">No unfinished tasks in the approved collection.</li>'}</ul></section><section class="panel today-journal"><div class="section-heading"><div><p class="eyebrow">ONE DAY / YOUR OWN WORDS</p><h2>Daily journal</h2></div><a href="${e(link('/vault/journal'))}">History →</a></div><p class="fine">Free-form Markdown. Use “Link in journal” beside a task to insert a wiki link, then save.</p>${journalContent}</section><section class="panel today-para"><div class="section-heading"><div><p class="eyebrow">KEEP CONTEXT NEARBY</p><h2>PARA</h2></div><a href="${e(link('/vault/para'))}">Browse →</a></div><div class="para-grid">${groups}</div></section></div>${undo}</div>`;
}

export function todayPage(workspace: Workspace, visitor: Visitor, runtime: VaultRuntime): string {
  return page(workspace.plan.title, `<div class="workbench today-workbench" data-workspace="${e(workspace.id)}">${conversationPanel(workspace, visitor)}<section class="canvas-region" aria-label="Today workspace"><div id="pending-update" role="status" hidden>The workspace changed. Your unfinished form has been kept. <button type="button" id="apply-update">Discard form edits and refresh</button></div>${todayCanvas(workspace, visitor, runtime)}</section></div>`, true);
}

export function approvalPage(visitor: Visitor, runtime: VaultRuntime): string {
  const apps = runtime.reviews();
  return page('Review vault apps', `<section class="approval-page"><p class="eyebrow">BROWSER-ONLY / EXPLICIT CONSENT</p><h1>Review your apps.</h1><p class="lead">Markdown files are candidates, not authority. Inspect the exact source and choose each permission yourself. Approval applies only to this revision; editing a definition suspends its permissions until you review it again.</p><p><a href="/today">← Back to Today</a></p>${apps.length ? apps.map((app, index) => `<article class="panel app-review"><div class="section-heading"><div><h2>${e(app.name)}</h2><p class="fine">${e(app.path)}</p></div><span class="tag">${e(app.status)}</span></div><dl class="facts"><div><dt>App ID</dt><dd>${e(app.id)}</dd></div><div><dt>Exact SHA-256 revision</dt><dd><code>${e(app.revision)}</code></dd></div></dl>${app.diagnostics.length ? `<ul class="app-diagnostics">${app.diagnostics.map(diagnostic => `<li><strong>${e(diagnostic.severity)} · ${e(diagnostic.code)}</strong> ${e(diagnostic.file)}:${diagnostic.line}:${diagnostic.column} — ${e(diagnostic.message)}</li>`).join('')}</ul>` : ''}<details class="definition-source" open><summary>Exact definition source</summary><pre><code>${e(app.source)}</code></pre></details>${app.status === 'invalid' ? '<p class="notice">This definition is invalid and cannot be approved. Correct the file, then reload this review.</p>' : `<form method="post" action="/vault/approve"><input type="hidden" name="csrf" value="${e(visitor.csrf)}"><input type="hidden" name="app" value="${e(app.id)}"><input type="hidden" name="revision" value="${e(app.revision)}"><fieldset><legend>Permissions for this exact revision</legend><p class="fine">Unchecked permissions are denied. Saving with no permissions revokes all access for this app. Existing grants are selected only for an active, unchanged revision.</p>${app.permissions.map((permission, permissionIndex) => `<label class="permission" for="permission-${index}-${permissionIndex}"><input id="permission-${index}-${permissionIndex}" type="checkbox" name="permissions" value="${e(permission)}"${app.status === 'active' && app.granted.includes(permission) ? ' checked' : ''}><span><code>${e(permission)}</code><small>${e(permission === 'notes:read' ? 'Read ordinary, untyped notes throughout the visible vault.' : permission.startsWith('read:') ? 'Read valid records of this document type.' : permission.startsWith('create:') ? 'Create records through declared actions.' : 'Update records through declared actions; no unrestricted file writes.')}</small></span></label>`).join('')}</fieldset><button class="primary">${app.status === 'active' ? 'Save exact permissions' : 'Approve selected permissions'}</button></form>`}</article>`).join('') : '<p class="empty">No app definitions were found in the vault’s .apps folder.</p>'}</section>`);
}
